name: Prepare Allure
description: Allure installation and folders
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get install allure
        mkdir -p allure-results
        touch allure-results/1.txt
        mkdir -p allure-report
        mkdir -p allure-history
      shell: bash